In [1]:
import pandas as pd

In [33]:
homelessness = pd.read_csv('../datasets/homelessness.csv')

homelessness.head()

,Unnamed: 0,region,state,individuals,family_members,state_pop
0,0,East South Central,Alabama,2570.0,864.0,4887681
1,1,Pacific,Alaska,1434.0,582.0,735139
2,2,Mountain,Arizona,7259.0,2606.0,7158024
3,3,West South Central,Arkansas,2280.0,432.0,3009733
4,4,Pacific,California,109008.0,20964.0,39461588

In [3]:
homelessness.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      51 non-null     int64
 1   region          51 non-null     object
 2   state           51 non-null     object
 3   individuals     51 non-null     float64
 4   family_members  51 non-null     float64
 5   state_pop       51 non-null     int64
dtypes: float64(2), int64(2), object(2)
memory usage: 2.5+ KB

In [4]:
homelessness.shape

(51, 6)

In [5]:
homelessness.describe()

       Unnamed: 0    individuals  family_members     state_pop
count   51.000000      51.000000       51.000000  5.100000e+01
mean    25.000000    7225.784314     3504.882353  6.405637e+06
std     14.866069   15991.025083     7805.411811  7.327258e+06
min      0.000000     434.000000       75.000000  5.776010e+05
25%     12.500000    1446.500000      592.000000  1.777414e+06
50%     25.000000    3082.000000     1482.000000  4.461153e+06
75%     37.500000    6781.500000     3196.000000  7.340946e+06
max     50.000000  109008.000000    52070.000000  3.946159e+07

In [6]:
homelessness.values

array([[0, 'East South Central', 'Alabama', 2570.0, 864.0, 4887681],
       [1, 'Pacific', 'Alaska', 1434.0, 582.0, 735139],
       [2, 'Mountain', 'Arizona', 7259.0, 2606.0, 7158024],
       [3, 'West South Central', 'Arkansas', 2280.0, 432.0, 3009733],
       [4, 'Pacific', 'California', 109008.0, 20964.0, 39461588],
       [5, 'Mountain', 'Colorado', 7607.0, 3250.0, 5691287],
       [6, 'New England', 'Connecticut', 2280.0, 1696.0, 3571520],
       [7, 'South Atlantic', 'Delaware', 708.0, 374.0, 965479],
       [8, 'South Atlantic', 'District of Columbia', 3770.0, 3134.0,
        701547],
       [9, 'South Atlantic', 'Florida', 21443.0, 9587.0, 21244317],
       [10, 'South Atlantic', 'Georgia', 6943.0, 2556.0, 10511131],
       [11, 'Pacific', 'Hawaii', 4131.0, 2399.0, 1420593],
       [12, 'Mountain', 'Idaho', 1297.0, 715.0, 1750536],
       [13, 'East North Central', 'Illinois', 6752.0, 3891.0, 12723071],
       [14, 'East North Central', 'Indiana', 3776.0, 1482.0, 6695497],
       [15, 'West North Central', 'Iowa', 1711.0, 1038.0, 3148618],
       [16, 'West North Central', 'Kansas', 1443.0, 773.0, 2911359],
       [17, 'East South Central', 'Kentucky', 2735.0, 953.0, 4461153],
       [18, 'West South Central', 'Louisiana', 2540.0, 519.0, 4659690],
       [19, 'New England', 'Maine', 1450.0, 1066.0, 1339057],
       [20, 'South Atlantic', 'Maryland', 4914.0, 2230.0, 6035802],
       [21, 'New England', 'Massachusetts', 6811.0, 13257.0, 6882635],
       [22, 'East North Central', 'Michigan', 5209.0, 3142.0, 9984072],
       [23, 'West North Central', 'Minnesota', 3993.0, 3250.0, 5606249],
       [24, 'East South Central', 'Mississippi', 1024.0, 328.0, 2981020],
       [25, 'West North Central', 'Missouri', 3776.0, 2107.0, 6121623],
       [26, 'Mountain', 'Montana', 983.0, 422.0, 1060665],
       [27, 'West North Central', 'Nebraska', 1745.0, 676.0, 1925614],
       [28, 'Mountain', 'Nevada', 7058.0, 486.0, 3027341],
       [29, 'New England', 'New Hampshire', 835.0, 615.0, 1353465],
       [30, 'Mid-Atlantic', 'New Jersey', 6048.0, 3350.0, 8886025],
       [31, 'Mountain', 'New Mexico', 1949.0, 602.0, 2092741],
       [32, 'Mid-Atlantic', 'New York', 39827.0, 52070.0, 19530351],
       [33, 'South Atlantic', 'North Carolina', 6451.0, 2817.0, 10381615],
       [34, 'West North Central', 'North Dakota', 467.0, 75.0, 758080],
       [35, 'East North Central', 'Ohio', 6929.0, 3320.0, 11676341],
       [36, 'West South Central', 'Oklahoma', 2823.0, 1048.0, 3940235],
       [37, 'Pacific', 'Oregon', 11139.0, 3337.0, 4181886],
       [38, 'Mid-Atlantic', 'Pennsylvania', 8163.0, 5349.0, 12800922],
       [39, 'New England', 'Rhode Island', 747.0, 354.0, 1058287],
       [40, 'South Atlantic', 'South Carolina', 3082.0, 851.0, 5084156],
       [41, 'West North Central', 'South Dakota', 836.0, 323.0, 878698],
       [42, 'East South Central', 'Tennessee', 6139.0, 1744.0, 6771631],
       [43, 'West South Central', 'Texas', 19199.0, 6111.0, 28628666],
       [44, 'Mountain', 'Utah', 1904.0, 972.0, 3153550],
       [45, 'New England', 'Vermont', 780.0, 511.0, 624358],
       [46, 'South Atlantic', 'Virginia', 3928.0, 2047.0, 8501286],
       [47, 'Pacific', 'Washington', 16424.0, 5880.0, 7523869],
       [48, 'South Atlantic', 'West Virginia', 1021.0, 222.0, 1804291],
       [49, 'East North Central', 'Wisconsin', 2740.0, 2167.0, 5807406],
       [50, 'Mountain', 'Wyoming', 434.0, 205.0, 577601]], dtype=object)

In [7]:
homelessness.columns

Index(['Unnamed: 0', 'region', 'state', 'individuals', 'family_members',
       'state_pop'],
      dtype='object')

In [30]:
homelessness.index

RangeIndex(start=0, stop=51, step=1)

In [36]:
homelessness['region']

0     East South Central
1                Pacific
2               Mountain
3     West South Central
4                Pacific
5               Mountain
6            New England
7         South Atlantic
8         South Atlantic
9         South Atlantic
10        South Atlantic
11               Pacific
12              Mountain
13    East North Central
14    East North Central
15    West North Central
16    West North Central
17    East South Central
18    West South Central
19           New England
20        South Atlantic
21           New England
22    East North Central
23    West North Central
24    East South Central
25    West North Central
26              Mountain
27    West North Central
28              Mountain
29           New England
30          Mid-Atlantic
31              Mountain
32          Mid-Atlantic
33        South Atlantic
34    West North Central
35    East North Central
36    West South Central
37               Pacific
38          Mid-Atlantic
39           New England
40        South Atlantic
41    West North Central
42    East South Central
43    West South Central
44              Mountain
45           New England
46        South Atlantic
47               Pacific
48        South Atlantic
49    East North Central
50              Mountain
Name: region, dtype: object

In [35]:
homelessness.sort_values('state_pop', ascending=False).head()

,Unnamed: 0,region,state,individuals,family_members,state_pop
4,4,Pacific,California,109008.0,20964.0,39461588
43,43,West South Central,Texas,19199.0,6111.0,28628666
9,9,South Atlantic,Florida,21443.0,9587.0,21244317
32,32,Mid-Atlantic,New York,39827.0,52070.0,19530351
38,38,Mid-Atlantic,Pennsylvania,8163.0,5349.0,12800922

In [42]:
homelessness.sort_values('state_pop', ascending=True)[['state','state_pop']][0:11]

                   state  state_pop
50               Wyoming     577601
45               Vermont     624358
8   District of Columbia     701547
1                 Alaska     735139
34          North Dakota     758080
41          South Dakota     878698
7               Delaware     965479
39          Rhode Island    1058287
26               Montana    1060665
19                 Maine    1339057
29         New Hampshire    1353465

In [43]:
homelessness.sort_values('state_pop', ascending=True)[['state','state_pop']].head(10)

                   state  state_pop
50               Wyoming     577601
45               Vermont     624358
8   District of Columbia     701547
1                 Alaska     735139
34          North Dakota     758080
41          South Dakota     878698
7               Delaware     965479
39          Rhode Island    1058287
26               Montana    1060665
19                 Maine    1339057

In [50]:
homelessness.loc[homelessness['state_pop'] > 10000000, 'region']

4                Pacific
9         South Atlantic
10        South Atlantic
13    East North Central
32          Mid-Atlantic
33        South Atlantic
35    East North Central
38          Mid-Atlantic
43    West South Central
Name: region, dtype: object

In [51]:
homelessness[homelessness['state_pop'] > 10000000]['region']

4                Pacific
9         South Atlantic
10        South Atlantic
13    East North Central
32          Mid-Atlantic
33        South Atlantic
35    East North Central
38          Mid-Atlantic
43    West South Central
Name: region, dtype: object

In [54]:
homelessness[['region','state_pop']]['region']

0     East South Central
1                Pacific
2               Mountain
3     West South Central
4                Pacific
5               Mountain
6            New England
7         South Atlantic
8         South Atlantic
9         South Atlantic
10        South Atlantic
11               Pacific
12              Mountain
13    East North Central
14    East North Central
15    West North Central
16    West North Central
17    East South Central
18    West South Central
19           New England
20        South Atlantic
21           New England
22    East North Central
23    West North Central
24    East South Central
25    West North Central
26              Mountain
27    West North Central
28              Mountain
29           New England
30          Mid-Atlantic
31              Mountain
32          Mid-Atlantic
33        South Atlantic
34    West North Central
35    East North Central
36    West South Central
37               Pacific
38          Mid-Atlantic
39           New England
40        South Atlantic
41    West North Central
42    East South Central
43    West South Central
44              Mountain
45           New England
46        South Atlantic
47               Pacific
48        South Atlantic
49    East North Central
50              Mountain
Name: region, dtype: object

In [29]:
states_around_mojave = ['California', 'Arizona', 'Nevada', 'Utah']

homelessness[['state','individuals','family_members','state_pop']][homelessness["state"].isin(states_around_mojave)].sort_values('state_pop', ascending=False)

         state  individuals  family_members  state_pop
4   California     109008.0         20964.0   39461588
2      Arizona       7259.0          2606.0    7158024
44        Utah       1904.0           972.0    3153550
28      Nevada       7058.0           486.0    3027341

In [55]:
homelessness['total'] = homelessness['individuals'] + homelessness['family_members']

homelessness[['state','individuals','family_members','total','state_pop']][homelessness['state'].isin(states_around_mojave)].sort_values('state_pop', ascending=False).head()

         state  individuals  family_members     total  state_pop
4   California     109008.0         20964.0  129972.0   39461588
2      Arizona       7259.0          2606.0    9865.0    7158024
44        Utah       1904.0           972.0    2876.0    3153550
28      Nevada       7058.0           486.0    7544.0    3027341

In [56]:
def iqr(column):
    return column.quantile(0.75) - column.quantile(0.25)
    
print(iqr(homelessness["total"]))
print(homelessness["total"].agg(iqr))

7130.0
7130.0

In [57]:
print(iqr(homelessness["state_pop"]))
print(homelessness["state_pop"].agg(iqr))

5563533.0
5563533.0

In [58]:
homelessness.drop_duplicates(subset=["region", "state"])[["region", "state"]]

                region                 state
0   East South Central               Alabama
1              Pacific                Alaska
2             Mountain               Arizona
3   West South Central              Arkansas
4              Pacific            California
5             Mountain              Colorado
6          New England           Connecticut
7       South Atlantic              Delaware
8       South Atlantic  District of Columbia
9       South Atlantic               Florida
10      South Atlantic               Georgia
11             Pacific                Hawaii
12            Mountain                 Idaho
13  East North Central              Illinois
14  East North Central               Indiana
15  West North Central                  Iowa
16  West North Central                Kansas
17  East South Central              Kentucky
18  West South Central             Louisiana
19         New England                 Maine
20      South Atlantic              Maryland
21         New England         Massachusetts
22  East North Central              Michigan
23  West North Central             Minnesota
24  East South Central           Mississippi
25  West North Central              Missouri
26            Mountain               Montana
27  West North Central              Nebraska
28            Mountain                Nevada
29         New England         New Hampshire
30        Mid-Atlantic            New Jersey
31            Mountain            New Mexico
32        Mid-Atlantic              New York
33      South Atlantic        North Carolina
34  West North Central          North Dakota
35  East North Central                  Ohio
36  West South Central              Oklahoma
37             Pacific                Oregon
38        Mid-Atlantic          Pennsylvania
39         New England          Rhode Island
40      South Atlantic        South Carolina
41  West North Central          South Dakota
42  East South Central             Tennessee
43  West South Central                 Texas
44            Mountain                  Utah
45         New England               Vermont
46      South Atlantic              Virginia
47             Pacific            Washington
48      South Atlantic         West Virginia
49  East North Central             Wisconsin
50            Mountain               Wyoming

In [61]:
import re

text = "south Atlantic "
text2 = text.lower()
pattern = r"south atlantic"

match = re.search(pattern, text2)
if match:
    text = "South Atlantic"
    print(text)
else:
    print("No match")

South Atlantic

In [64]:
state_ind = homelessness.set_index("state").sort_values("state", ascending=False)

print(state_ind)

                      Unnamed: 0              region  individuals  \
state
Wyoming                       50            Mountain        434.0
Wisconsin                     49  East North Central       2740.0
West Virginia                 48      South Atlantic       1021.0
Washington                    47             Pacific      16424.0
Virginia                      46      South Atlantic       3928.0
Vermont                       45         New England        780.0
Utah                          44            Mountain       1904.0
Texas                         43  West South Central      19199.0
Tennessee                     42  East South Central       6139.0
South Dakota                  41  West North Central        836.0
South Carolina                40      South Atlantic       3082.0
Rhode Island                  39         New England        747.0
Pennsylvania                  38        Mid-Atlantic       8163.0
Oregon                        37             Pacific      11139.0
Oklahoma                      36  West South Central       2823.0
Ohio                          35  East North Central       6929.0
North Dakota                  34  West North Central        467.0
North Carolina                33      South Atlantic       6451.0
New York                      32        Mid-Atlantic      39827.0
New Mexico                    31            Mountain       1949.0
New Jersey                    30        Mid-Atlantic       6048.0
New Hampshire                 29         New England        835.0
Nevada                        28            Mountain       7058.0
Nebraska                      27  West North Central       1745.0
Montana                       26            Mountain        983.0
Missouri                      25  West North Central       3776.0
Mississippi                   24  East South Central       1024.0
Minnesota                     23  West North Central       3993.0
Michigan                      22  East North Central       5209.0
Massachusetts                 21         New England       6811.0
Maryland                      20      South Atlantic       4914.0
Maine                         19         New England       1450.0
Louisiana                     18  West South Central       2540.0
Kentucky                      17  East South Central       2735.0
Kansas                        16  West North Central       1443.0
Iowa                          15  West North Central       1711.0
Indiana                       14  East North Central       3776.0
Illinois                      13  East North Central       6752.0
Idaho                         12            Mountain       1297.0
Hawaii                        11             Pacific       4131.0
Georgia                       10      South Atlantic       6943.0
Florida                        9      South Atlantic      21443.0
District of Columbia           8      South Atlantic       3770.0
Delaware                       7      South Atlantic        708.0
Connecticut                    6         New England       2280.0
Colorado                       5            Mountain       7607.0
California                     4             Pacific     109008.0
Arkansas                       3  West South Central       2280.0
Arizona                        2            Mountain       7259.0
Alaska                         1             Pacific       1434.0
Alabama                        0  East South Central       2570.0

                      family_members  state_pop     total
state
Wyoming                        205.0     577601     639.0
Wisconsin                     2167.0    5807406    4907.0
West Virginia                  222.0    1804291    1243.0
Washington                    5880.0    7523869   22304.0
Virginia                      2047.0    8501286    5975.0
Vermont                        511.0     624358    1291.0
Utah                           972.0    3153550    2876.0
Texas                         6111.0   28628666   25310.0
Tennessee                     1744.0    6771631    7883.0
South Dakota                   323.0     878698    1159.0
South Carolina                 851.0    5084156    3933.0
Rhode Island                   354.0    1058287    1101.0
Pennsylvania                  5349.0   12800922   13512.0
Oregon                        3337.0    4181886   14476.0
Oklahoma                      1048.0    3940235    3871.0
Ohio                          3320.0   11676341   10249.0
North Dakota                    75.0     758080     542.0
North Carolina                2817.0   10381615    9268.0
New York                     52070.0   19530351   91897.0
New Mexico                     602.0    2092741    2551.0
New Jersey                    3350.0    8886025    9398.0
New Hampshire                  615.0    1353465    1450.0
Nevada                         486.0    3027341    7544.0
Nebraska                       676.0    1925614    2421.0
Montana                        422.0    1060665    1405.0
Missouri                      2107.0    6121623    5883.0
Mississippi                    328.0    2981020    1352.0
Minnesota                     3250.0    5606249    7243.0
Michigan                      3142.0    9984072    8351.0
Massachusetts                13257.0    6882635   20068.0
Maryland                      2230.0    6035802    7144.0
Maine                         1066.0    1339057    2516.0
Louisiana                      519.0    4659690    3059.0
Kentucky                       953.0    4461153    3688.0
Kansas                         773.0    2911359    2216.0
Iowa                          1038.0    3148618    2749.0
Indiana                       1482.0    6695497    5258.0
Illinois                      3891.0   12723071   10643.0
Idaho                          715.0    1750536    2012.0
Hawaii                        2399.0    1420593    6530.0
Georgia                       2556.0   10511131    9499.0
Florida                       9587.0   21244317   31030.0
District of Columbia          3134.0     701547    6904.0
Delaware                       374.0     965479    1082.0
Connecticut                   1696.0    3571520    3976.0
Colorado                      3250.0    5691287   10857.0
California                   20964.0   39461588  129972.0
Arkansas                       432.0    3009733    2712.0
Arizona                       2606.0    7158024    9865.0
Alaska                         582.0     735139    2016.0
Alabama                        864.0    4887681    3434.0

In [65]:
# Reset the temperatures_ind index, keeping its contents
state_ind.reset_index()

,state,Unnamed: 0,region,individuals,family_members,state_pop,total
0,Wyoming,50,Mountain,434.0,205.0,577601,639.0
1,Wisconsin,49,East North Central,2740.0,2167.0,5807406,4907.0
2,West Virginia,48,South Atlantic,1021.0,222.0,1804291,1243.0
3,Washington,47,Pacific,16424.0,5880.0,7523869,22304.0
4,Virginia,46,South Atlantic,3928.0,2047.0,8501286,5975.0
5,Vermont,45,New England,780.0,511.0,624358,1291.0
6,Utah,44,Mountain,1904.0,972.0,3153550,2876.0
7,Texas,43,West South Central,19199.0,6111.0,28628666,25310.0
8,Tennessee,42,East South Central,6139.0,1744.0,6771631,7883.0
9,South Dakota,41,West North Central,836.0,323.0,878698,1159.0
10,South Carolina,40,South Atlantic,3082.0,851.0,5084156,3933.0
11,Rhode Island,39,New England,747.0,354.0,1058287,1101.0
12,Pennsylvania,38,Mid-Atlantic,8163.0,5349.0,12800922,13512.0
13,Oregon,37,Pacific,11139.0,3337.0,4181886,14476.0
14,Oklahoma,36,West South Central,2823.0,1048.0,3940235,3871.0
15,Ohio,35,East North Central,6929.0,3320.0,11676341,10249.0
16,North Dakota,34,West North Central,467.0,75.0,758080,542.0
17,North Carolina,33,South Atlantic,6451.0,2817.0,10381615,9268.0
18,New York,32,Mid-Atlantic,39827.0,52070.0,19530351,91897.0
19,New Mexico,31,Mountain,1949.0,602.0,2092741,2551.0
20,New Jersey,30,Mid-Atlantic,6048.0,3350.0,8886025,9398.0
21,New Hampshire,29,New England,835.0,615.0,1353465,1450.0
22,Nevada,28,Mountain,7058.0,486.0,3027341,7544.0
23,Nebraska,27,West North Central,1745.0,676.0,1925614,2421.0
24,Montana,26,Mountain,983.0,422.0,1060665,1405.0
25,Missouri,25,West North Central,3776.0,2107.0,6121623,5883.0
26,Mississippi,24,East South Central,1024.0,328.0,2981020,1352.0
27,Minnesota,23,West North Central,3993.0,3250.0,5606249,7243.0
28,Michigan,22,East North Central,5209.0,3142.0,9984072,8351.0
29,Massachusetts,21,New England,6811.0,13257.0,6882635,20068.0
30,Maryland,20,South Atlantic,4914.0,2230.0,6035802,7144.0
31,Maine,19,New England,1450.0,1066.0,1339057,2516.0
32,Louisiana,18,West South Central,2540.0,519.0,4659690,3059.0
33,Kentucky,17,East South Central,2735.0,953.0,4461153,3688.0
34,Kansas,16,West North Central,1443.0,773.0,2911359,2216.0
35,Iowa,15,West North Central,1711.0,1038.0,3148618,2749.0
36,Indiana,14,East North Central,3776.0,1482.0,6695497,5258.0
37,Illinois,13,East North Central,6752.0,3891.0,12723071,10643.0
38,Idaho,12,Mountain,1297.0,715.0,1750536,2012.0
39,Hawaii,11,Pacific,4131.0,2399.0,1420593,6530.0
40,Georgia,10,South Atlantic,6943.0,2556.0,10511131,9499.0
41,Florida,9,South Atlantic,21443.0,9587.0,21244317,31030.0
42,District of Columbia,8,South Atlantic,3770.0,3134.0,701547,6904.0
43,Delaware,7,South Atlantic,708.0,374.0,965479,1082.0
44,Connecticut,6,New England,2280.0,1696.0,3571520,3976.0
45,Colorado,5,Mountain,7607.0,3250.0,5691287,10857.0
46,California,4,Pacific,109008.0,20964.0,39461588,129972.0
47,Arkansas,3,West South Central,2280.0,432.0,3009733,2712.0
48,Arizona,2,Mountain,7259.0,2606.0,7158024,9865.0
49,Alaska,1,Pacific,1434.0,582.0,735139,2016.0
50,Alabama,0,East South Central,2570.0,864.0,4887681,3434.0

In [66]:
state_ind.reset_index(drop=True)

,Unnamed: 0,region,individuals,family_members,state_pop,total
0,50,Mountain,434.0,205.0,577601,639.0
1,49,East North Central,2740.0,2167.0,5807406,4907.0
2,48,South Atlantic,1021.0,222.0,1804291,1243.0
3,47,Pacific,16424.0,5880.0,7523869,22304.0
4,46,South Atlantic,3928.0,2047.0,8501286,5975.0
5,45,New England,780.0,511.0,624358,1291.0
6,44,Mountain,1904.0,972.0,3153550,2876.0
7,43,West South Central,19199.0,6111.0,28628666,25310.0
8,42,East South Central,6139.0,1744.0,6771631,7883.0
9,41,West North Central,836.0,323.0,878698,1159.0
10,40,South Atlantic,3082.0,851.0,5084156,3933.0
11,39,New England,747.0,354.0,1058287,1101.0
12,38,Mid-Atlantic,8163.0,5349.0,12800922,13512.0
13,37,Pacific,11139.0,3337.0,4181886,14476.0
14,36,West South Central,2823.0,1048.0,3940235,3871.0
15,35,East North Central,6929.0,3320.0,11676341,10249.0
16,34,West North Central,467.0,75.0,758080,542.0
17,33,South Atlantic,6451.0,2817.0,10381615,9268.0
18,32,Mid-Atlantic,39827.0,52070.0,19530351,91897.0
19,31,Mountain,1949.0,602.0,2092741,2551.0
20,30,Mid-Atlantic,6048.0,3350.0,8886025,9398.0
21,29,New England,835.0,615.0,1353465,1450.0
22,28,Mountain,7058.0,486.0,3027341,7544.0
23,27,West North Central,1745.0,676.0,1925614,2421.0
24,26,Mountain,983.0,422.0,1060665,1405.0
25,25,West North Central,3776.0,2107.0,6121623,5883.0
26,24,East South Central,1024.0,328.0,2981020,1352.0
27,23,West North Central,3993.0,3250.0,5606249,7243.0
28,22,East North Central,5209.0,3142.0,9984072,8351.0
29,21,New England,6811.0,13257.0,6882635,20068.0
30,20,South Atlantic,4914.0,2230.0,6035802,7144.0
31,19,New England,1450.0,1066.0,1339057,2516.0
32,18,West South Central,2540.0,519.0,4659690,3059.0
33,17,East South Central,2735.0,953.0,4461153,3688.0
34,16,West North Central,1443.0,773.0,2911359,2216.0
35,15,West North Central,1711.0,1038.0,3148618,2749.0
36,14,East North Central,3776.0,1482.0,6695497,5258.0
37,13,East North Central,6752.0,3891.0,12723071,10643.0
38,12,Mountain,1297.0,715.0,1750536,2012.0
39,11,Pacific,4131.0,2399.0,1420593,6530.0
40,10,South Atlantic,6943.0,2556.0,10511131,9499.0
41,9,South Atlantic,21443.0,9587.0,21244317,31030.0
42,8,South Atlantic,3770.0,3134.0,701547,6904.0
43,7,South Atlantic,708.0,374.0,965479,1082.0
44,6,New England,2280.0,1696.0,3571520,3976.0
45,5,Mountain,7607.0,3250.0,5691287,10857.0
46,4,Pacific,109008.0,20964.0,39461588,129972.0
47,3,West South Central,2280.0,432.0,3009733,2712.0
48,2,Mountain,7259.0,2606.0,7158024,9865.0
49,1,Pacific,1434.0,582.0,735139,2016.0
50,0,East South Central,2570.0,864.0,4887681,3434.0

In [67]:
state_ind.loc[states_around_mojave]

,Unnamed: 0,region,individuals,family_members,state_pop,total
state,,,,,,
California,4,Pacific,109008.0,20964.0,39461588,129972.0
Arizona,2,Mountain,7259.0,2606.0,7158024,9865.0
Nevada,28,Mountain,7058.0,486.0,3027341,7544.0
Utah,44,Mountain,1904.0,972.0,3153550,2876.0

In [68]:
state_multi_ind = homelessness.set_index(["region", "state"])

rows_to_keep = [("Pacific", "California"), ("Mountain", "Arizona")]

state_multi_ind.loc[rows_to_keep]

,,Unnamed: 0,individuals,family_members,state_pop,total
region,state,,,,,
Pacific,California,4,109008.0,20964.0,39461588,129972.0
Mountain,Arizona,2,7259.0,2606.0,7158024,9865.0

In [69]:
state_multi_ind.sort_index(level=["region", "state"], ascending = [True, False])

                                         Unnamed: 0  individuals  \
region             state
East North Central Wisconsin                     49       2740.0
                   Ohio                          35       6929.0
                   Michigan                      22       5209.0
                   Indiana                       14       3776.0
                   Illinois                      13       6752.0
East South Central Tennessee                     42       6139.0
                   Mississippi                   24       1024.0
                   Kentucky                      17       2735.0
                   Alabama                        0       2570.0
Mid-Atlantic       Pennsylvania                  38       8163.0
                   New York                      32      39827.0
                   New Jersey                    30       6048.0
Mountain           Wyoming                       50        434.0
                   Utah                          44       1904.0
                   New Mexico                    31       1949.0
                   Nevada                        28       7058.0
                   Montana                       26        983.0
                   Idaho                         12       1297.0
                   Colorado                       5       7607.0
                   Arizona                        2       7259.0
New England        Vermont                       45        780.0
                   Rhode Island                  39        747.0
                   New Hampshire                 29        835.0
                   Massachusetts                 21       6811.0
                   Maine                         19       1450.0
                   Connecticut                    6       2280.0
Pacific            Washington                    47      16424.0
                   Oregon                        37      11139.0
                   Hawaii                        11       4131.0
                   California                     4     109008.0
                   Alaska                         1       1434.0
South Atlantic     West Virginia                 48       1021.0
                   Virginia                      46       3928.0
                   South Carolina                40       3082.0
                   North Carolina                33       6451.0
                   Maryland                      20       4914.0
                   Georgia                       10       6943.0
                   Florida                        9      21443.0
                   District of Columbia           8       3770.0
                   Delaware                       7        708.0
West North Central South Dakota                  41        836.0
                   North Dakota                  34        467.0
                   Nebraska                      27       1745.0
                   Missouri                      25       3776.0
                   Minnesota                     23       3993.0
                   Kansas                        16       1443.0
                   Iowa                          15       1711.0
West South Central Texas                         43      19199.0
                   Oklahoma                      36       2823.0
                   Louisiana                     18       2540.0
                   Arkansas                       3       2280.0

                                         family_members  state_pop     total
region             state
East North Central Wisconsin                     2167.0    5807406    4907.0
                   Ohio                          3320.0   11676341   10249.0
                   Michigan                      3142.0    9984072    8351.0
                   Indiana                       1482.0    6695497    5258.0
                   Illinois                      3891.0   12723071   10643.0
East South Central Tennessee                     1744.0    6771631    7883.0
                   Mississippi                    328.0    2981020    1352.0
                   Kentucky                       953.0    4461153    3688.0
                   Alabama                        864.0    4887681    3434.0
Mid-Atlantic       Pennsylvania                  5349.0   12800922   13512.0
                   New York                     52070.0   19530351   91897.0
                   New Jersey                    3350.0    8886025    9398.0
Mountain           Wyoming                        205.0     577601     639.0
                   Utah                           972.0    3153550    2876.0
                   New Mexico                     602.0    2092741    2551.0
                   Nevada                         486.0    3027341    7544.0
                   Montana                        422.0    1060665    1405.0
                   Idaho                          715.0    1750536    2012.0
                   Colorado                      3250.0    5691287   10857.0
                   Arizona                       2606.0    7158024    9865.0
New England        Vermont                        511.0     624358    1291.0
                   Rhode Island                   354.0    1058287    1101.0
                   New Hampshire                  615.0    1353465    1450.0
                   Massachusetts                13257.0    6882635   20068.0
                   Maine                         1066.0    1339057    2516.0
                   Connecticut                   1696.0    3571520    3976.0
Pacific            Washington                    5880.0    7523869   22304.0
                   Oregon                        3337.0    4181886   14476.0
                   Hawaii                        2399.0    1420593    6530.0
                   California                   20964.0   39461588  129972.0
                   Alaska                         582.0     735139    2016.0
South Atlantic     West Virginia                  222.0    1804291    1243.0
                   Virginia                      2047.0    8501286    5975.0
                   South Carolina                 851.0    5084156    3933.0
                   North Carolina                2817.0   10381615    9268.0
                   Maryland                      2230.0    6035802    7144.0
                   Georgia                       2556.0   10511131    9499.0
                   Florida                       9587.0   21244317   31030.0
                   District of Columbia          3134.0     701547    6904.0
                   Delaware                       374.0     965479    1082.0
West North Central South Dakota                   323.0     878698    1159.0
                   North Dakota                    75.0     758080     542.0
                   Nebraska                       676.0    1925614    2421.0
                   Missouri                      2107.0    6121623    5883.0
                   Minnesota                     3250.0    5606249    7243.0
                   Kansas                         773.0    2911359    2216.0
                   Iowa                          1038.0    3148618    2749.0
West South Central Texas                         6111.0   28628666   25310.0
                   Oklahoma                      1048.0    3940235    3871.0
                   Louisiana                      519.0    4659690    3059.0
                   Arkansas                       432.0    3009733    2712.0

In [22]:
state_srt = state_ind.sort_index()

state_srt.loc['Alabama':'Arkansas']

,Unnamed: 0,region,individuals,family_members,state_pop,total
state,,,,,,
Alabama,0,East South Central,2570.0,864.0,4887681,3434.0
Alaska,1,Pacific,1434.0,582.0,735139,2016.0
Arizona,2,Mountain,7259.0,2606.0,7158024,9865.0
Arkansas,3,West South Central,2280.0,432.0,3009733,2712.0

In [23]:
state_srt.loc['Alabama':'Arkansas','region':'state_pop']

                      region  individuals  family_members  state_pop
state
Alabama   East South Central       2570.0           864.0    4887681
Alaska               Pacific       1434.0           582.0     735139
Arizona             Mountain       7259.0          2606.0    7158024
Arkansas  West South Central       2280.0           432.0    3009733

In [24]:
homelessness.iloc[22, 1]

'East North Central'

In [25]:
homelessness.isna().head()

   Unnamed: 0  region  state  individuals  family_members  state_pop  total
0       False   False  False        False           False      False  False
1       False   False  False        False           False      False  False
2       False   False  False        False           False      False  False
3       False   False  False        False           False      False  False
4       False   False  False        False           False      False  False

In [26]:
homelessness.isna().any().head()

Unnamed: 0        False
region            False
state             False
individuals       False
family_members    False
dtype: bool

In [27]:
copy_of_homelessness = homelessness.copy()

copy_of_homelessness.dropna()

copy_of_homelessness.isna().any()

Unnamed: 0        False
region            False
state             False
individuals       False
family_members    False
state_pop         False
total             False
dtype: bool