In [1]:
import pandas as pd

df = pd.read_csv('../datasets/Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [3]:
df['SepalLengthCm'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 150 entries, 0 to 149
Series name: SepalLengthCm
Non-Null Count  Dtype
--------------  -----
150 non-null    float64
dtypes: float64(1)
memory usage: 1.3 KB

In [4]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [5]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [6]:
import numpy as np

df.loc[0, 'SepalLengthCm':'PetalWidthCm'] = np.nan
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  149 non-null    float64
 2   SepalWidthCm   149 non-null    float64
 3   PetalLengthCm  149 non-null    float64
 4   PetalWidthCm   149 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [7]:
df2 = df.copy()

In [8]:
df2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            NaN           NaN            NaN           NaN  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [9]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            NaN           NaN            NaN           NaN  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [10]:
df.loc[df.isnull().any(axis=1)]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            NaN           NaN            NaN           NaN  Iris-setosa

In [11]:
filter = df2['Species'] == 'Iris-setosa'
print(filter)

0       True
1       True
2       True
3       True
4       True
       ...
145    False
146    False
147    False
148    False
149    False
Name: Species, Length: 150, dtype: bool

In [12]:
df2.where(filter, inplace=True)

In [13]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             50 non-null     float64
 1   SepalLengthCm  49 non-null     float64
 2   SepalWidthCm   49 non-null     float64
 3   PetalLengthCm  49 non-null     float64
 4   PetalWidthCm   49 non-null     float64
 5   Species        50 non-null     object
dtypes: float64(5), object(1)
memory usage: 7.2+ KB

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  149 non-null    float64
 2   SepalWidthCm   149 non-null    float64
 3   PetalLengthCm  149 non-null    float64
 4   PetalWidthCm   149 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [15]:
df2.where(filter, inplace=True)

In [16]:
df[['SepalLengthCm']] = df[['SepalLengthCm']].fillna(value=df.groupby('Species')['SepalLengthCm'].mean().values[0])
df[['SepalWidthCm']] = df[['SepalWidthCm']].fillna(value=df.groupby('Species')['SepalWidthCm'].mean().values[0])
df[['PetalLengthCm']] = df[['PetalLengthCm']].fillna(value=df.groupby('Species')['PetalLengthCm'].mean().values[0])
df[['PetalWidthCm']] = df[['PetalWidthCm']].fillna(value=df.groupby('Species')['PetalWidthCm'].mean().values[0])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [18]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1       5.004082      3.416327       1.465306      0.244898  Iris-setosa
1   2       4.900000      3.000000       1.400000      0.200000  Iris-setosa
2   3       4.700000      3.200000       1.300000      0.200000  Iris-setosa
3   4       4.600000      3.100000       1.500000      0.200000  Iris-setosa
4   5       5.000000      3.600000       1.400000      0.200000  Iris-setosa

In [19]:
print(df.groupby('Species')['SepalLengthCm'].mean().values[0])

# or

print(df[df['Species'] == 'Iris-setosa']['SepalLengthCm'].mean())

# or

print(df.query("Species == 'Iris-setosa'")['SepalLengthCm'].mean())

5.004081632653062
5.004081632653062
5.004081632653062

In [20]:
df[['SepalLengthCm']] = df[['SepalLengthCm']].fillna(value=df2.groupby('Species')['SepalLengthCm'].mean().values[0])

In [21]:
df2.groupby('Species')['SepalLengthCm'].mean().values[0]

5.004081632653061

In [22]:
df[df['Species'] == 'Iris-setosa']['SepalLengthCm'].mean()

5.004081632653062

In [23]:
print(df[['Species']] == 'Iris-setosa')

     Species
0       True
1       True
2       True
3       True
4       True
..       ...
145    False
146    False
147    False
148    False
149    False

[150 rows x 1 columns]

In [24]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1       5.004082      3.416327       1.465306      0.244898  Iris-setosa
1   2       4.900000      3.000000       1.400000      0.200000  Iris-setosa
2   3       4.700000      3.200000       1.300000      0.200000  Iris-setosa
3   4       4.600000      3.100000       1.500000      0.200000  Iris-setosa
4   5       5.000000      3.600000       1.400000      0.200000  Iris-setosa

In [25]:
df.loc[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Id, SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm, Species]
Index: []

In [26]:
np.max(df['PetalLengthCm'].values[0])

1.4653061224489796