### Loading Dataset

In [52]:
import pandas as pd

df = pd.read_csv('../datasets/Iris.csv')

In [28]:
df.tail(2)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [29]:
print(df.iloc[-1])

Id                          150
SepalLengthCm               5.9
SepalWidthCm                3.0
PetalLengthCm               5.1
PetalWidthCm                1.8
Species          Iris-virginica
Name: 149, dtype: object

### Handling Duplicates

+ Duplicate values are rows of data that have the same data points for every column of our dataset
+ This can distort our analysis and should be avoided

In [53]:
df.drop(columns=['Id'], inplace=True)

In [56]:
# Count how many duplicates there are
df.duplicated().sum()

3

In [59]:
# Examine the affected rows
df.loc[df.duplicated(keep=False)]

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
9              4.9           3.1            1.5           0.1     Iris-setosa
34             4.9           3.1            1.5           0.1     Iris-setosa
37             4.9           3.1            1.5           0.1     Iris-setosa
101            5.8           2.7            5.1           1.9  Iris-virginica
142            5.8           2.7            5.1           1.9  Iris-virginica

In [49]:
# Check for duplicates in the DataFrame
duplicates = df[df.duplicated()]
print(duplicates)

Empty DataFrame
Columns: [SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm, Species]
Index: []

In [47]:
print(df.iloc[101])

SepalLengthCm               5.8
SepalWidthCm                2.7
PetalLengthCm               5.1
PetalWidthCm                1.9
Species          Iris-virginica
Name: 101, dtype: object

### Drop the duplicate values

In [48]:
df.drop_duplicates(inplace=True)

### Data Type Conversion

In [51]:
# Check the data types of columns

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 147 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  147 non-null    float64
 1   SepalWidthCm   147 non-null    float64
 2   PetalLengthCm  147 non-null    float64
 3   PetalWidthCm   147 non-null    float64
 4   Species        147 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.9+ KB

In [60]:
# Convert a column to a datetyme format

df['SepalLengthCm'] = df['SepalLengthCm'].astype(str)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  150 non-null    object
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object
dtypes: float64(3), object(2)
memory usage: 6.0+ KB

In [61]:
# Convert the column to float

df['SepalLengthCm'] = df['SepalLengthCm'].astype(float)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

### Renaming Columns

In [62]:
# Rename a column using rename method

df.rename(columns={'Species': 'Type'}, inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Type           150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [64]:
# Rename the column back to its original name

df.rename(columns={'Type': 'Species'}, inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB