In [1]:
import pandas as pd

df = pd.read_csv('../datasets/Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [3]:
df.sample(10)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
12,13,4.8,3.0,1.4,0.1,Iris-setosa
26,27,5.0,3.4,1.6,0.4,Iris-setosa
25,26,5.0,3.0,1.6,0.2,Iris-setosa
44,45,5.1,3.8,1.9,0.4,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
96,97,5.7,2.9,4.2,1.3,Iris-versicolor
145,146,6.7,3.0,5.2,2.3,Iris-virginica
116,117,6.5,3.0,5.5,1.8,Iris-virginica
8,9,4.4,2.9,1.4,0.2,Iris-setosa
73,74,6.1,2.8,4.7,1.2,Iris-versicolor

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [38]:
df['SepalLengthCm'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 150 entries, 0 to 149
Series name: SepalLengthCm
Non-Null Count  Dtype
--------------  -----
150 non-null    float64
dtypes: float64(1)
memory usage: 1.3 KB

In [39]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [40]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [41]:
df2 = df.copy()

In [66]:
import numpy as np

df.loc[0, 'SepalLengthCm':'PetalWidthCm'] = np.nan
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  149 non-null    float64
 2   SepalWidthCm   149 non-null    float64
 3   PetalLengthCm  149 non-null    float64
 4   PetalWidthCm   149 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [47]:
df2.drop(columns=['Id'], inplace=True)

In [51]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  149 non-null    float64
 1   SepalWidthCm   149 non-null    float64
 2   PetalLengthCm  149 non-null    float64
 3   PetalWidthCm   149 non-null    float64
 4   Species        150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [52]:
df2.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            NaN           NaN            NaN           NaN  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [58]:
# Get the index of rows with missing values
missing_idx = df2.isnull().any(axis=1).index[df2.isnull().any(axis=1)]
print("Indices of rows with missing values:", missing_idx)

Indices of rows with missing values: Index([0], dtype='int64')

In [ ]:
df2[df2.isnull().any(axis=1)]

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            NaN           NaN            NaN           NaN  Iris-setosa

In [60]:
filter = df2['Species'] == 'Iris-setosa'
print(filter)

0       True
1       True
2       True
3       True
4       True
       ...
145    False
146    False
147    False
148    False
149    False
Name: Species, Length: 150, dtype: bool

In [61]:
df2.where(filter, inplace=True)

In [62]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  49 non-null     float64
 1   SepalWidthCm   49 non-null     float64
 2   PetalLengthCm  49 non-null     float64
 3   PetalWidthCm   49 non-null     float64
 4   Species        50 non-null     object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  149 non-null    float64
 2   SepalWidthCm   149 non-null    float64
 3   PetalLengthCm  149 non-null    float64
 4   PetalWidthCm   149 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [68]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            NaN           NaN            NaN           NaN  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [69]:
df[['SepalLengthCm']] = df[['SepalLengthCm']].fillna(value=df.groupby('Species')['SepalLengthCm'].mean().values[0])
df[['SepalWidthCm']] = df[['SepalWidthCm']].fillna(value=df.groupby('Species')['SepalWidthCm'].mean().values[0])
df[['PetalLengthCm']] = df[['PetalLengthCm']].fillna(value=df.groupby('Species')['PetalLengthCm'].mean().values[0])
df[['PetalWidthCm']] = df[['PetalWidthCm']].fillna(value=df.groupby('Species')['PetalWidthCm'].mean().values[0])

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [71]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1       5.004082      3.416327       1.465306      0.244898  Iris-setosa
1   2       4.900000      3.000000       1.400000      0.200000  Iris-setosa
2   3       4.700000      3.200000       1.300000      0.200000  Iris-setosa
3   4       4.600000      3.100000       1.500000      0.200000  Iris-setosa
4   5       5.000000      3.600000       1.400000      0.200000  Iris-setosa

In [72]:
print(df.groupby('Species')['SepalLengthCm'].mean().values[0])

# or

print(df[df['Species'] == 'Iris-setosa']['SepalLengthCm'].mean())

# or

print(df.query("Species == 'Iris-setosa'")['SepalLengthCm'].mean())

5.004081632653062
5.004081632653062
5.004081632653062

In [20]:
df[['SepalLengthCm']] = df[['SepalLengthCm']].fillna(value=df2.groupby('Species')['SepalLengthCm'].mean().values[0])

In [21]:
df2.groupby('Species')['SepalLengthCm'].mean().values[0]

5.004081632653061

In [22]:
df[df['Species'] == 'Iris-setosa']['SepalLengthCm'].mean()

5.004081632653062

In [23]:
print(df[['Species']] == 'Iris-setosa')

     Species
0       True
1       True
2       True
3       True
4       True
..       ...
145    False
146    False
147    False
148    False
149    False

[150 rows x 1 columns]

In [24]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1       5.004082      3.416327       1.465306      0.244898  Iris-setosa
1   2       4.900000      3.000000       1.400000      0.200000  Iris-setosa
2   3       4.700000      3.200000       1.300000      0.200000  Iris-setosa
3   4       4.600000      3.100000       1.500000      0.200000  Iris-setosa
4   5       5.000000      3.600000       1.400000      0.200000  Iris-setosa

In [25]:
df.loc[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Id, SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm, Species]
Index: []

In [73]:
np.max(df['PetalLengthCm'].values[0])

1.4653061224489796

In [1]:
import pandas as pd

df_json = pd.read_json('../datasets/cloud_run_log.json')
df_json

,insertId,jsonPayload,resource,timestamp,labels,logName,receiveTimestamp,protoPayload,severity
0,MTIzNjQ5MjQ2Nw,"{'detailedState': 'CONFIRMED', 'detailedCatego...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 08:57:15.950779+00:00,{'servicehealth.googleapis.com/updated_fields'...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T08:57:27.860582655Z,NaN,NaN
1,MjAxMzUxNjUyNw,{'description': 'We are experiencing an issue...,"{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 10:19:07.409427+00:00,{'servicehealth.googleapis.com/updated_fields'...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T10:19:14.751857856Z,NaN,NaN
2,MzU1MDk2NDk5Ng,{'symptom': 'Impacted customer requests will g...,"{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 12:01:22.871072+00:00,{'servicehealth.googleapis.com/new_event': 'fa...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T12:01:32.948606583Z,NaN,NaN
3,MTUxODUzNTI2Ng,"{'detailedState': 'CONFIRMED', 'updateTime': '...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 12:51:38.584692+00:00,{'servicehealth.googleapis.com/new_event': 'fa...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T12:51:49.971038596Z,NaN,NaN
4,MTAzNTcxNTUwNQ,"{'state': 'CLOSED', 'impactedProductIds': '['9...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 14:14:19.276306+00:00,{'servicehealth.googleapis.com/new_event': 'fa...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T14:14:28.715743316Z,NaN,NaN
5,MTE3NTk2NzYxNA,"{'relevance': 'PARTIALLY_RELATED', 'detailedCa...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-05 08:24:51.675912+00:00,{'servicehealth.googleapis.com/new_event': 'tr...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-05T08:25:17.036987087Z,NaN,NaN
6,ODIyNzAwMDMw,{'title': 'Cloud Monitoring users may experien...,"{'type': 'servicehealth.googleapis.com/Event',...",2025-09-05 08:46:40.760997+00:00,{'servicehealth.googleapis.com/updated_fields'...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-05T08:46:54.883854693Z,NaN,NaN
7,Nzc5NzI3NjM2,"{'workaround': 'None at this time.', 'symptom'...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-05 10:17:03.524701+00:00,{'servicehealth.googleapis.com/new_event': 'fa...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-05T10:17:16.901710396Z,NaN,NaN
8,14kjmce3b5hq,NaN,"{'type': 'project', 'labels': {'project_id': '...",2025-09-05 12:13:49.480093+00:00,NaN,projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-05T12:13:50.489145620Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
9,-ql5nzzdpf1c,NaN,"{'type': 'project', 'labels': {'project_id': '...",2025-09-06 08:33:22.363606+00:00,NaN,projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-06T08:33:22.929288110Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
10,-yw9ja5e3ibvg,NaN,"{'type': 'project', 'labels': {'project_id': '...",2025-09-06 11:14:57.674278+00:00,NaN,projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-06T11:14:57.771336824Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
11,-1dpm8xe7v8gw,NaN,"{'type': 'project', 'labels': {'project_id': '...",2025-09-07 00:43:38.408466+00:00,NaN,projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-07T00:43:38.954636398Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
12,1ob4xddkjxk,NaN,"{'type': 'project', 'labels': {'project_id': '...",2025-09-07 00:44:28.614811+00:00,NaN,projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-07T00:44:29.295206119Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
13,-vmcy91e2vsge,NaN,"{'type': 'project', 'labels': {'project_id': '...",2025-09-08 15:59:08.892615+00:00,NaN,projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-08T15:59:09.686671518Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
14,-6md34he3vvi6,NaN,"{'type': 'project', 'labels': {'project_id': '...",2025-09-08 17:59:36.154368+00:00,NaN,projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-08T17:59:36.784604038Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
15,-ql5nzze1k8xi,NaN,"{'type': 'project', 'labels': {'project_id': '...",2025-09-09 02:46:59.023498+00:00,NaN,projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-09T02:46:59.947809343Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
16,5lwvdle9ziuw,NaN,"{'type': 'project', 'labels': {'project_id': '...",2025-09-09 05:58:24.318174+00:00,NaN,projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-09T05:58:24.805558994Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO

In [5]:
df_json.isnull().sum()

insertId            0
jsonPayload         9
resource            0
timestamp           0
labels              9
logName             0
receiveTimestamp    0
protoPayload        8
severity            8
dtype: int64

In [2]:
import pandas as pd

# Check for missing values in df_json
print(df_json.isnull().sum())

insertId            0
jsonPayload         9
resource            0
timestamp           0
labels              9
logName             0
receiveTimestamp    0
protoPayload        8
severity            8
dtype: int64

In [ ]:

for i in range(len(df_json.columns) -1):
    df_json[df_json.columns[i]] = df_json[df_json.columns[i]].map(lambda x: {} if pd.isna(x) else x)
df_json

,insertId,jsonPayload,resource,timestamp,labels,logName,receiveTimestamp,protoPayload,severity
0,MTIzNjQ5MjQ2Nw,"{'detailedState': 'CONFIRMED', 'detailedCatego...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 08:57:15.950779+00:00,{'servicehealth.googleapis.com/updated_fields'...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T08:57:27.860582655Z,{},NaN
1,MjAxMzUxNjUyNw,{'description': 'We are experiencing an issue...,"{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 10:19:07.409427+00:00,{'servicehealth.googleapis.com/updated_fields'...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T10:19:14.751857856Z,{},NaN
2,MzU1MDk2NDk5Ng,{'symptom': 'Impacted customer requests will g...,"{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 12:01:22.871072+00:00,{'servicehealth.googleapis.com/new_event': 'fa...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T12:01:32.948606583Z,{},NaN
3,MTUxODUzNTI2Ng,"{'detailedState': 'CONFIRMED', 'updateTime': '...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 12:51:38.584692+00:00,{'servicehealth.googleapis.com/new_event': 'fa...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T12:51:49.971038596Z,{},NaN
4,MTAzNTcxNTUwNQ,"{'state': 'CLOSED', 'impactedProductIds': '['9...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 14:14:19.276306+00:00,{'servicehealth.googleapis.com/new_event': 'fa...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T14:14:28.715743316Z,{},NaN
5,MTE3NTk2NzYxNA,"{'relevance': 'PARTIALLY_RELATED', 'detailedCa...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-05 08:24:51.675912+00:00,{'servicehealth.googleapis.com/new_event': 'tr...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-05T08:25:17.036987087Z,{},NaN
6,ODIyNzAwMDMw,{'title': 'Cloud Monitoring users may experien...,"{'type': 'servicehealth.googleapis.com/Event',...",2025-09-05 08:46:40.760997+00:00,{'servicehealth.googleapis.com/updated_fields'...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-05T08:46:54.883854693Z,{},NaN
7,Nzc5NzI3NjM2,"{'workaround': 'None at this time.', 'symptom'...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-05 10:17:03.524701+00:00,{'servicehealth.googleapis.com/new_event': 'fa...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-05T10:17:16.901710396Z,{},NaN
8,14kjmce3b5hq,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-05 12:13:49.480093+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-05T12:13:50.489145620Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
9,-ql5nzzdpf1c,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-06 08:33:22.363606+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-06T08:33:22.929288110Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
10,-yw9ja5e3ibvg,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-06 11:14:57.674278+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-06T11:14:57.771336824Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
11,-1dpm8xe7v8gw,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-07 00:43:38.408466+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-07T00:43:38.954636398Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
12,1ob4xddkjxk,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-07 00:44:28.614811+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-07T00:44:29.295206119Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
13,-vmcy91e2vsge,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-08 15:59:08.892615+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-08T15:59:09.686671518Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
14,-6md34he3vvi6,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-08 17:59:36.154368+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-08T17:59:36.784604038Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
15,-ql5nzze1k8xi,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-09 02:46:59.023498+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-09T02:46:59.947809343Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
16,5lwvdle9ziuw,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-09 05:58:24.318174+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-09T05:58:24.805558994Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO

In [7]:
df_json[df_json.columns[len(df_json.columns)-1]] = df_json[df_json.columns[len(df_json.columns)-1]].map(lambda x: 'UNKNOWN' if pd.isna(x) else x)
df_json

,insertId,jsonPayload,resource,timestamp,labels,logName,receiveTimestamp,protoPayload,severity
0,MTIzNjQ5MjQ2Nw,"{'detailedState': 'CONFIRMED', 'detailedCatego...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 08:57:15.950779+00:00,{'servicehealth.googleapis.com/updated_fields'...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T08:57:27.860582655Z,{},UNKNOWN
1,MjAxMzUxNjUyNw,{'description': 'We are experiencing an issue...,"{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 10:19:07.409427+00:00,{'servicehealth.googleapis.com/updated_fields'...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T10:19:14.751857856Z,{},UNKNOWN
2,MzU1MDk2NDk5Ng,{'symptom': 'Impacted customer requests will g...,"{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 12:01:22.871072+00:00,{'servicehealth.googleapis.com/new_event': 'fa...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T12:01:32.948606583Z,{},UNKNOWN
3,MTUxODUzNTI2Ng,"{'detailedState': 'CONFIRMED', 'updateTime': '...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 12:51:38.584692+00:00,{'servicehealth.googleapis.com/new_event': 'fa...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T12:51:49.971038596Z,{},UNKNOWN
4,MTAzNTcxNTUwNQ,"{'state': 'CLOSED', 'impactedProductIds': '['9...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 14:14:19.276306+00:00,{'servicehealth.googleapis.com/new_event': 'fa...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T14:14:28.715743316Z,{},UNKNOWN
5,MTE3NTk2NzYxNA,"{'relevance': 'PARTIALLY_RELATED', 'detailedCa...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-05 08:24:51.675912+00:00,{'servicehealth.googleapis.com/new_event': 'tr...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-05T08:25:17.036987087Z,{},UNKNOWN
6,ODIyNzAwMDMw,{'title': 'Cloud Monitoring users may experien...,"{'type': 'servicehealth.googleapis.com/Event',...",2025-09-05 08:46:40.760997+00:00,{'servicehealth.googleapis.com/updated_fields'...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-05T08:46:54.883854693Z,{},UNKNOWN
7,Nzc5NzI3NjM2,"{'workaround': 'None at this time.', 'symptom'...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-05 10:17:03.524701+00:00,{'servicehealth.googleapis.com/new_event': 'fa...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-05T10:17:16.901710396Z,{},UNKNOWN
8,14kjmce3b5hq,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-05 12:13:49.480093+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-05T12:13:50.489145620Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
9,-ql5nzzdpf1c,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-06 08:33:22.363606+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-06T08:33:22.929288110Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
10,-yw9ja5e3ibvg,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-06 11:14:57.674278+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-06T11:14:57.771336824Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
11,-1dpm8xe7v8gw,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-07 00:43:38.408466+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-07T00:43:38.954636398Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
12,1ob4xddkjxk,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-07 00:44:28.614811+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-07T00:44:29.295206119Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
13,-vmcy91e2vsge,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-08 15:59:08.892615+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-08T15:59:09.686671518Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
14,-6md34he3vvi6,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-08 17:59:36.154368+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-08T17:59:36.784604038Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
15,-ql5nzze1k8xi,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-09 02:46:59.023498+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-09T02:46:59.947809343Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
16,5lwvdle9ziuw,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-09 05:58:24.318174+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-09T05:58:24.805558994Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO

,insertId,jsonPayload,resource,timestamp,labels,logName,receiveTimestamp,protoPayload,severity
0,MTIzNjQ5MjQ2Nw,"{'detailedState': 'CONFIRMED', 'detailedCatego...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 08:57:15.950779+00:00,{'servicehealth.googleapis.com/updated_fields'...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T08:57:27.860582655Z,{},UNKNOWN
1,MjAxMzUxNjUyNw,{'description': 'We are experiencing an issue...,"{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 10:19:07.409427+00:00,{'servicehealth.googleapis.com/updated_fields'...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T10:19:14.751857856Z,{},UNKNOWN
2,MzU1MDk2NDk5Ng,{'symptom': 'Impacted customer requests will g...,"{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 12:01:22.871072+00:00,{'servicehealth.googleapis.com/new_event': 'fa...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T12:01:32.948606583Z,{},UNKNOWN
3,MTUxODUzNTI2Ng,"{'detailedState': 'CONFIRMED', 'updateTime': '...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 12:51:38.584692+00:00,{'servicehealth.googleapis.com/new_event': 'fa...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T12:51:49.971038596Z,{},UNKNOWN
4,MTAzNTcxNTUwNQ,"{'state': 'CLOSED', 'impactedProductIds': '['9...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-03 14:14:19.276306+00:00,{'servicehealth.googleapis.com/new_event': 'fa...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-03T14:14:28.715743316Z,{},UNKNOWN
5,MTE3NTk2NzYxNA,"{'relevance': 'PARTIALLY_RELATED', 'detailedCa...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-05 08:24:51.675912+00:00,{'servicehealth.googleapis.com/new_event': 'tr...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-05T08:25:17.036987087Z,{},UNKNOWN
6,ODIyNzAwMDMw,{'title': 'Cloud Monitoring users may experien...,"{'type': 'servicehealth.googleapis.com/Event',...",2025-09-05 08:46:40.760997+00:00,{'servicehealth.googleapis.com/updated_fields'...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-05T08:46:54.883854693Z,{},UNKNOWN
7,Nzc5NzI3NjM2,"{'workaround': 'None at this time.', 'symptom'...","{'type': 'servicehealth.googleapis.com/Event',...",2025-09-05 10:17:03.524701+00:00,{'servicehealth.googleapis.com/new_event': 'fa...,projects/figsarai-2fe08/logs/servicehealth.goo...,2025-09-05T10:17:16.901710396Z,{},UNKNOWN
8,14kjmce3b5hq,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-05 12:13:49.480093+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-05T12:13:50.489145620Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
9,-ql5nzzdpf1c,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-06 08:33:22.363606+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-06T08:33:22.929288110Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
10,-yw9ja5e3ibvg,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-06 11:14:57.674278+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-06T11:14:57.771336824Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
11,-1dpm8xe7v8gw,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-07 00:43:38.408466+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-07T00:43:38.954636398Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
12,1ob4xddkjxk,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-07 00:44:28.614811+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-07T00:44:29.295206119Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
13,-vmcy91e2vsge,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-08 15:59:08.892615+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-08T15:59:09.686671518Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
14,-6md34he3vvi6,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-08 17:59:36.154368+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-08T17:59:36.784604038Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
15,-ql5nzze1k8xi,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-09 02:46:59.023498+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-09T02:46:59.947809343Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO
16,5lwvdle9ziuw,{},"{'type': 'project', 'labels': {'project_id': '...",2025-09-09 05:58:24.318174+00:00,{},projects/figsarai-2fe08/logs/cloudaudit.google...,2025-09-09T05:58:24.805558994Z,{'@type': 'type.googleapis.com/google.cloud.au...,INFO