## loc

loc (Label-based indexing)<br>
loc is primarily label-based, meaning use the actual row and column labels (names) to select data.<br><br>
Row Selection: Provide the label(s) of the row(s) that we want.
- Column Selection: Provide the label(s) of the column(s) that we want.
- Slicing: When slicing with loc, both the start and stop labels are inclusive.

In [4]:
# Create a DataFrame
import pandas as pd

data = {'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]}
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'])
print(df)

      A  B  C
row1  1  4  7
row2  2  5  8
row3  3  6  9

In [5]:
data2 = data

In [7]:
df2 =  pd.DataFrame(data2)
df2

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [12]:
# Select a single row by label
df.loc['row2']

A    2
B    5
C    8
Name: row2, dtype: int64

In [9]:
df.loc[['row2']]

      A  B  C
row2  2  5  8

In [10]:
df.loc[['row1','row2', 'row3']]

      A  B  C
row1  1  4  7
row2  2  5  8
row3  3  6  9

In [ ]:
# Select multiple rows by labels
df.loc[['row1', 'row3']]

      A  B  C
row1  1  4  7
row3  3  6  9

In [13]:
# Select a single cell by row and column labels
df.loc['row1', 'A']

1

In [14]:
# Select a range of rows and columns (inclusive slicing)
df.loc['row1':'row2', 'A':'C']

      A  B  C
row1  1  4  7
row2  2  5  8

In [18]:
work_df = df.loc[:,['A','C']]
work_df

      A  C
row1  1  7
row2  2  8
row3  3  9

In [16]:
df.loc[:,'A']

row1    1
row2    2
row3    3
Name: A, dtype: int64

In [20]:
# Conditional selection with loc
df.loc[df['A'] > 1, ['A','C']]

      A  C
row2  2  8
row3  3  9

In [21]:
df.loc[df['A'] > 1, 'A':'C']

      A  B  C
row2  2  5  8
row3  3  6  9

## iloc

iloc (Integer-location based indexing)<br>
iloc is primarily integer-location based, meaning use the integer positions (from 0 to n-1) of rows and columns to select data.<br><br>
- Row Selection: Provide the integer position(s) of the row(s) taht we want.
- Column Selection: Provide the integer position(s) of the column(s) that we want.
- Slicing: When slicing with iloc, the start position is inclusive, and the stop position is exclusive (just like standard Python list slicing).

In [22]:
# Select a single row by integer position
df.iloc[1] # Selects the second row (index 1)

A    2
B    5
C    8
Name: row2, dtype: int64

In [23]:
df.iloc[[1]]

      A  B  C
row2  2  5  8

In [25]:
# Select multiple rows by integer positions
df.iloc[[0, 2]] # Selects the first and third rows

      A  B  C
row1  1  4  7
row3  3  6  9

In [9]:
# Select a single cell by integer row and column positions
df.iloc[0, 1] # Selects the cell at row 0, column 1

4

In [26]:
df.loc['row1', 'B']

4

In [29]:
# Select a range of rows and columns (exclusive slicing for stop)
df.iloc[0:2, 0:2] # Selects rows 0 and 1, columns 0 and 1

      A  B
row1  1  4
row2  2  5

## When to use which?

*   **Use `loc`** when we care about the actual names of our rows and columns. This is often the case when our DataFrame has meaningful labels (e.g., dates as index, specific sensor names as columns).
*   **Use `iloc`** when we need to access data by its position in the DataFrame, regardless of its labels. This is common when iterating through rows, selecting the first/last 'n' rows, or when the row/column labels are not unique or meaningful for our current task.

## Reset Index

If we reset the index of a DataFrame, the default integer index (0, 1, 2...) becomes a column, and we get a new default integer index.

In [30]:
df_reset = df.reset_index()
print(df_reset)

  index  A  B  C
0  row1  1  4  7
1  row2  2  5  8
2  row3  3  6  9

In [31]:
df

      A  B  C
row1  1  4  7
row2  2  5  8
row3  3  6  9

In [32]:
df_reset.loc[0]

index    row1
A           1
B           4
C           7
Name: 0, dtype: object

In [33]:
df_reset.iloc[0]

index    row1
A           1
B           4
C           7
Name: 0, dtype: object